import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Jason",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Marcus",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Red hooded sweatshirt",
      slug: "red-hooded-sweatshirt",
      category: "Hoodie",
      image: "/Red-Hoodie.jpeg",
      price: 29.9,
      brand: "BandOfHoode",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Blank hooded sweatshirt  with zipper in front",
    },
    {
      name: "Purple hoodie",
      slug: "purple-hoodie",
      category: "Hoodie",
      image: "/Purple-Hoodie-2.jpeg",
      price: 49.9,
      brand: "BandOfHoode",
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: "Blank hooded sweatshirt",
    },
    {
      name: "Tracksuit top",
      slug: "tracksuit-top",
      category: "Track Suit",
      image: "/Orange-Hoodie.jpeg",
      price: 49.9,
      brand: "BandOfHoode",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Blank tracksuit top",
    },
    {
      name: "Purple/Back colorblock hoodie",
      slug: "purple-black-colorblockk-hoodie",
      category: "Hoodie",
      image: "/Purple-Hoodie.jpeg",
      price: 25.9,
      brand: "BandOfHoode",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Blank colorblock hooded sweatshirt with zipper in front",
    },
    {
      name: "Blue sweatshirt",
      slug: "blue-sweatshirt",
      category: "Hoodie",
      image: "/Blue-Hoodie.jpeg",
      price: 10.9,
      brand: "BandOfHoode",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Blank sweatshirt ",
    },
    {
      name: "Red/black jacket",
      slug: "red-black-jack",
      category: "Hoodie",
      image: "/Red-Hoodie-3.jpeg",
      price: 49.9,
      brand: "BandOfHoode",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Men's hooded jacket with half zip",
    },
    {
      name: "Red sweatshirt",
      slug: "red-sweatshirt",
      category: "Hoodie",
      image: "/Red-Hoodie-2.jpeg",
      price: 49.9,
      brand: "BandOfHoode",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Men's hooded red sweatshirt",
    },
    {
      name: "Green hooded jacket",
      slug: "green-hooded-jacket",
      category: "jacket",
      image: "/green-Hoodie.jpeg",
      price: 49.9,
      brand: "BandOfHoode",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Blank hooded sweatshirt, with half ziper",
    },
    {
      name: "BlueGray colorblock hoodie",
      slug: "bluegray-colorblock-hooide",
      category: "Hoodie",
      image: "/Blue-Hoodie-2.jpeg",
      price: 49.9,
      brand: "BandOfHoode",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Blank colorblock hooded sweatshirt with zipper",
    },
  ],
};

export default data;
